# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1C1924)
$foreground = rgb(F8E6FF)
$color0 = rgb(433F4C)
$color1 = rgb(0D0D39)
$color2 = rgb(110F3D)
$color3 = rgb(493877)
$color4 = rgb(493877)
$color5 = rgb(76598F)
$color6 = rgb(B189BF)
$color7 = rgb(EDD3F7)
$color8 = rgb(A693AD)
$color9 = rgb(12114C)
$color10 = rgb(171551)
$color11 = rgb(614A9F)
$color12 = rgb(614A9F)
$color13 = rgb(9E77BF)
$color14 = rgb(ECB7FF)
$color15 = rgb(EDD3F7)
