# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F8E6FF
background         #1C1924
cursor             #887DA8

active_tab_foreground     #1C1924
active_tab_background     #F8E6FF
inactive_tab_foreground   #F8E6FF
inactive_tab_background   #1C1924

active_border_color   #F8E6FF
inactive_border_color #1C1924
bell_border_color     #0D0D39

color0      #433F4C
color1		#0D0D39
color2		#110F3D
color3		#493877
color4		#493877
color5		#76598F
color6		#B189BF
color7		#EDD3F7
color8		#A693AD
color9		#12114C
color10		#171551
color11		#614A9F
color12		#614A9F
color13		#9E77BF
color14		#ECB7FF
color15		#EDD3F7
